import type { Metadata } from 'next';
import { cookies } from 'next/headers';

import { EDarkMode } from '@/shared/enums/cookie-values';

import { DARK_MODE } from '@/shared/consts/cookie-names';
import { DARK } from '@/shared/consts/theme-class-names';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type TRootLayout = Readonly<{
  children: React.ReactNode;
}>;

const RootLayout = async ({ children }: TRootLayout) => {
  const cookieStore = await cookies();
  const darkMode = cookieStore.get(DARK_MODE)?.value === EDarkMode.ENABLED;

  return (
    <html className={darkMode ? DARK : undefined}>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
};

export default RootLayout;
