import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type TRootLayout = Readonly<{
  children: React.ReactNode;
}>;

const RootLayout = async ({ children }: TRootLayout) => (
  <html>
    <body className={`antialiased`}>{children}</body>
  </html>
);

export default RootLayout;
