export const enum EDriverEntityKeys {
  EMAIL = 'email',
  FIRST_NAME = 'first_name',
  LAST_NAME = 'last_name',
  PHONE_NUMBER = 'phone_number',
  PHONE_NUMBER_HASH = 'phone_number_hash',
  CITY = 'city',
  PASSWORD = 'password',
  CAR_NUMBER = 'car_number',
  CAR_NUMBER_HASH = 'car_number_hash',
  CAR_BRAND = 'car_brand',
  CAR_MODEL = 'car_model',
  CAR_COLOR = 'car_color',
  TERMS = 'terms',
}
