export const enum EErrorKeys {
  REQUIRED_FIELD = 'requiredField',
  MINIMUM_REQUIRED_CHARACTERS = 'minimumRequiredCharacters',
  ONLY_LETTERS = 'onlyLetters',
  ONLY_LETTERS_AND_DIGITS = 'onlyLettersAndDigits',
  INVALID_EMAIL = 'invalidEmail',
  INVALID_PHONE_NUMBER = 'invalidPhoneNumber',
  FIRST_NAME_MINIMUM_CHARACTERS = 'firstNameMinimumCharacters',
  FIRST_NAME_CHARACTERS = 'firstNameCharacters',
  LAST_NAME_MINIMUM_CHARACTERS = 'lastNameMinimumCharacters',
  LAST_NAME_CHARACTERS = 'lastNameCharacters',
  PASSWORD_MINIMUM_CHARACTERS = 'passwordMinimumCharacters',
  PASSWORD_UPPER_CASE = 'passwordUpperCase',
  PASSWORD_LOWER_CASE = 'passwordLowerCase',
  PASSWORD_DIGIT = 'passwordDigit',
  PASSWORD_SPECIAL_CHARACTER = 'passwordSpecialCharacter',
  PASSWORDS_MUST_MATCH = 'passwordMustMatch',
  CAR_REGISTRATION_NUMBER_CHARACTERS = 'carRegistrationNumberCharacters',
  REQUIRED_FACIAL_RECOGNITION = 'requiredFacialRecognition',
}
