name: Playwright E2E tests

on: [pull_request, workflow_dispatch]

env:
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  REGISTER_DRIVER_TOKEN_SECRET_KEY: ${{ secrets.REGISTER_DRIVER_TOKEN_SECRET_KEY }}
  API_URL: ${{ secrets.API_URL }}
  API_KEY: ${{ secrets.API_KEY }}
  ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
  ENCRYPT_IV: ${{ secrets.ENCRYPT_IV }}
  DOMAIN_URL: 'localhost:3000'
  ENVIRONMENT: 'development'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js 20.15.0
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i --force

      - name: Install playwright browsers
        run: npx playwright install

      - name: Run playwright tests
        run: npm run test:e2e

      - name: Upload playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: tests/e2e/reports/
          retention-days: 30
